# Generated by Django 5.0.2 on 2024-02-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo_perfil',
            field=models.ImageField(blank=True, upload_to='profile_photos/'),
        ),
    ]
