# Generated by Django 5.0.2 on 2024-02-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo_perfil',
            new_name='profile_image',
        ),
    ]
